/**
 * Client-side export for HTML slide decks generated by ProDeck.
 *
 * PDF  — html2canvas captures each slide exactly as rendered in the browser,
 *         assembled into a jsPDF landscape document.
 *
 * PPTX — DOM-to-PPTX reconstruction: each visible HTML element becomes a
 *         native pptxgenjs primitive (shape, text box, image) so every element
 *         is individually editable in PowerPoint and Google Slides.
 */

// ── Constants ─────────────────────────────────────────────────────────────────

// 16:9 slide at 72pt/in  →  960 × 540 pt  (13.333" × 7.5")
const SLIDE_W_PT = 960;
const SLIDE_H_PT = 540;

// Viewport used when rendering slides in the hidden iframe
const IFRAME_W = 1280;
const IFRAME_H = 720;

// pptxgenjs LAYOUT_WIDE dimensions in inches
const SLIDE_W_IN = 13.333;
const SLIDE_H_IN = 7.5;

// ── Types ─────────────────────────────────────────────────────────────────────

interface TextNode {
  text: string;
  x: number; // 0-1 fraction of slide width
  y: number; // 0-1 fraction of slide height
  w: number;
  h: number;
  fontSize: number; // CSS px
  bold: boolean;
  italic: boolean;
  underline: boolean;
  color: string; // hex without #
  fontFace: string;
  align: 'left' | 'center' | 'right';
}

// ── iframe lifecycle ──────────────────────────────────────────────────────────

function createSlideIframe(html: string): Promise<HTMLIFrameElement> {
  return new Promise((resolve, reject) => {
    const iframe = document.createElement('iframe');
    iframe.style.cssText = [
      'position:fixed',
      'left:-9999px',
      'top:0',
      `width:${IFRAME_W}px`,
      `height:${IFRAME_H}px`,
      'border:none',
      'visibility:hidden',
      'pointer-events:none',
    ].join(';');

    iframe.onload = async () => {
      try {
        const win = iframe.contentWindow;
        if (!win) { reject(new Error('iframe window unavailable')); return; }
        // Wait for web fonts to finish loading so text renders correctly
        await win.document.fonts.ready;
        // One extra frame for any deferred layout work
        await new Promise(r => requestAnimationFrame(r));
        resolve(iframe);
      } catch (e) {
        reject(e);
      }
    };

    iframe.onerror = () => reject(new Error('iframe failed to load'));
    iframe.srcdoc = html;
    document.body.appendChild(iframe);
  });
}

function removeIframe(iframe: HTMLIFrameElement) {
  try { document.body.removeChild(iframe); } catch { /* already removed */ }
}

// ── Slide element detection ───────────────────────────────────────────────────
// Mirrors the priority order in slide-generator.ts → countSlides()

function findSlideElements(doc: Document): HTMLElement[] {
  // 1. explicit data attributes
  const byAttr = Array.from(doc.querySelectorAll<HTMLElement>('[data-slide],[data-idx]'));
  if (byAttr.length > 0) return byAttr;

  // 2. standalone class token  (matches "slide" but not "slide-content" etc.)
  const byClass = Array.from(doc.querySelectorAll<HTMLElement>('*')).filter(el => {
    const tokens = el.className && typeof el.className === 'string'
      ? el.className.split(/\s+/)
      : [];
    return tokens.some(t => t === 'slide' || t === 'page' || t === 'slide-page');
  });
  if (byClass.length > 0) return byClass;

  // 3. top-level <section> elements
  const bySec = Array.from(doc.querySelectorAll<HTMLElement>('body > section'));
  if (bySec.length > 1) return bySec;

  // 4. whole body as a single slide
  const body = doc.body;
  return body ? [body] : [];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** "rgb(r, g, b)" | "rgba(r,g,b,a)" | "#rrggbb" → "rrggbb" (no #) */
function rgbToHex(css: string): string | null {
  if (!css || css === 'transparent' || css === 'none') return null;
  if (/^#([0-9a-f]{3,8})$/i.test(css.trim())) {
    const h = css.trim().slice(1);
    if (h.length === 3) return h[0]+h[0]+h[1]+h[1]+h[2]+h[2];
    return h.slice(0, 6);
  }
  const m = css.match(/rgba?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);
  if (!m) return null;
  return [m[1], m[2], m[3]]
    .map(n => parseInt(n).toString(16).padStart(2, '0'))
    .join('');
}

/** First font family from a CSS font-family string, stripped of quotes */
function primaryFontFamily(fontFamily: string): string {
  const first = fontFamily.split(',')[0].trim().replace(/['"]/g, '');
  return first || 'Arial';
}

/** Direct text-node children only (avoids duplicating text already covered by child elements) */
function collectDirectText(el: Element): string {
  return Array.from(el.childNodes)
    .filter(n => n.nodeType === Node.TEXT_NODE)
    .map(n => n.textContent?.trim() ?? '')
    .filter(Boolean)
    .join(' ')
    .trim();
}

/** Parse "linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)" into pptxgenjs gradient */
function parseLinearGradient(css: string): { type: 'gradient'; angle: number; stops: { position: number; color: string }[] } | null {
  const gradMatch = css.match(/linear-gradient\s*\(([^)]+)\)/i);
  if (!gradMatch) return null;
  const inner = gradMatch[1];

  // Extract angle (default 180 = top-to-bottom)
  let angle = 180;
  const angleMatch = inner.match(/^(-?\d+(?:\.\d+)?deg)/i);
  if (angleMatch) angle = parseFloat(angleMatch[1]);

  // Extract color stops
  const stopRe = /(#[0-9a-f]{3,8}|rgba?\([^)]+\))\s+(\d+(?:\.\d+)?)%/gi;
  const stops: { position: number; color: string }[] = [];
  let m: RegExpExecArray | null;
  while ((m = stopRe.exec(inner)) !== null) {
    const hex = rgbToHex(m[1]);
    if (hex) stops.push({ position: parseFloat(m[2]), color: hex });
  }

  if (stops.length < 2) return null;
  return { type: 'gradient', angle, stops };
}

/** Serialize an SVG element to a PNG base64 data URL */
async function svgToBase64Png(svg: SVGElement): Promise<string> {
  const w = svg.clientWidth || svg.getBoundingClientRect().width || 64;
  const h = svg.clientHeight || svg.getBoundingClientRect().height || 64;
  const svgStr = new XMLSerializer().serializeToString(svg);
  const svgBlob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);
  return new Promise<string>((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width  = w;
      canvas.height = h;
      canvas.getContext('2d')!.drawImage(img, 0, 0, w, h);
      URL.revokeObjectURL(url);
      resolve(canvas.toDataURL('image/png'));
    };
    img.onerror = () => { URL.revokeObjectURL(url); reject(new Error('SVG render failed')); };
    img.src = url;
  });
}

/** Fetch an image URL and return it as a base64 data URI */
async function fetchToBase64(url: string): Promise<string> {
  try {
    const res = await fetch(url, { mode: 'cors' });
    const blob = await res.blob();
    return new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return ''; // skip images that can't be fetched (CORS, etc.)
  }
}

// ── PPTX DOM walker ───────────────────────────────────────────────────────────

const SKIP_TAGS = new Set(['script', 'style', 'noscript', 'meta', 'link', 'head']);

async function domToPptxSlide(
  slideEl: HTMLElement,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  slide: any, // pptxgenjs Slide — imported dynamically
  iframeWin: Window,
): Promise<void> {
  const sr = slideEl.getBoundingClientRect();
  if (!sr.width || !sr.height) return;

  // Helper: convert pixel rect (relative to slide) to pptxgenjs inches
  function px(val: number, dim: 'w' | 'h'): number {
    return dim === 'w'
      ? (val / sr.width)  * SLIDE_W_IN
      : (val / sr.height) * SLIDE_H_IN;
  }
  function pos(r: DOMRect) {
    return {
      x: px(r.left - sr.left, 'w'),
      y: px(r.top  - sr.top,  'h'),
      w: px(r.width,           'w'),
      h: px(r.height,          'h'),
    };
  }

  const slideSt = iframeWin.getComputedStyle(slideEl);

  // ── Slide background ──────────────────────────────────────────────────────
  const bgImg = slideSt.backgroundImage;
  if (bgImg && bgImg !== 'none') {
    if (bgImg.includes('gradient')) {
      const grad = parseLinearGradient(bgImg);
      if (grad) {
        // pptxgenjs slide.background with gradient
        slide.background = { fill: grad };
      } else {
        const fallback = rgbToHex(slideSt.backgroundColor);
        if (fallback) slide.background = { color: fallback };
      }
    } else {
      // background-image: url(...)  — use as full-slide image
      const urlMatch = bgImg.match(/url\(["']?([^"')]+)["']?\)/);
      if (urlMatch) {
        const data = await fetchToBase64(urlMatch[1]);
        if (data) slide.background = { data };
      }
    }
  } else {
    const bgColor = rgbToHex(slideSt.backgroundColor);
    if (bgColor) slide.background = { color: bgColor };
  }

  // ── Recursive element walker ──────────────────────────────────────────────
  async function walk(el: Element): Promise<void> {
    const tag = el.tagName?.toLowerCase() ?? '';
    if (SKIP_TAGS.has(tag)) return;

    const st = iframeWin.getComputedStyle(el as HTMLElement);
    if (st.display === 'none' || st.visibility === 'hidden') return;

    const opacity = parseFloat(st.opacity);
    if (!isNaN(opacity) && opacity === 0) return;

    const r = (el as HTMLElement).getBoundingClientRect();
    // Skip zero-size or fully outside slide bounds
    if (r.width < 1 || r.height < 1) return;
    if (r.right < sr.left || r.left > sr.right) return;
    if (r.bottom < sr.top || r.top > sr.bottom) return;

    const { x, y, w, h } = pos(r);
    // Clamp negatives (partially off-top of slide)
    const cx = Math.max(0, x);
    const cy = Math.max(0, y);
    const cw = Math.min(w, SLIDE_W_IN - cx);
    const ch = Math.min(h, SLIDE_H_IN - cy);
    if (cw < 0.01 || ch < 0.01) return;

    // ── <img> ──────────────────────────────────────────────────────────────
    if (tag === 'img') {
      const src = (el as HTMLImageElement).src;
      if (src) {
        const data = await fetchToBase64(src);
        if (data) slide.addImage({ data, x: cx, y: cy, w: cw, h: ch, sizing: { type: 'cover', w: cw, h: ch } });
      }
      return; // don't recurse into img
    }

    // ── <svg> ──────────────────────────────────────────────────────────────
    if (tag === 'svg') {
      try {
        const data = await svgToBase64Png(el as SVGElement);
        slide.addImage({ data, x: cx, y: cy, w: cw, h: ch });
      } catch { /* skip unrenderable SVGs */ }
      return; // SVGs are self-contained
    }

    // ── Background image (CSS url()) ───────────────────────────────────────
    const bgI = st.backgroundImage;
    if (bgI && bgI !== 'none' && bgI.includes('url(') && !bgI.includes('gradient')) {
      const urlMatch = bgI.match(/url\(["']?([^"')]+)["']?\)/);
      if (urlMatch) {
        const data = await fetchToBase64(urlMatch[1]);
        if (data) {
          slide.addImage({ data, x: cx, y: cy, w: cw, h: ch, sizing: { type: 'cover', w: cw, h: ch } });
        }
      }
      // fall through — may still have child text
    } else if (bgI && bgI !== 'none' && bgI.includes('gradient')) {
      // Gradient overlay shape
      const grad = parseLinearGradient(bgI);
      if (grad) {
        slide.addShape('rect', {
          x: cx, y: cy, w: cw, h: ch,
          fill: grad,
          line: { type: 'none' },
        });
      } else {
        const c = rgbToHex(st.backgroundColor);
        if (c && st.backgroundColor !== 'rgba(0, 0, 0, 0)') {
          slide.addShape('rect', { x: cx, y: cy, w: cw, h: ch, fill: { color: c }, line: { type: 'none' } });
        }
      }
    } else {
      // Solid background color (skip transparent/inherit)
      const bgc = st.backgroundColor;
      if (bgc && bgc !== 'rgba(0, 0, 0, 0)' && bgc !== 'transparent') {
        const c = rgbToHex(bgc);
        if (c) {
          slide.addShape('rect', { x: cx, y: cy, w: cw, h: ch, fill: { color: c }, line: { type: 'none' } });
        }
      }
    }

    // ── Direct text content ────────────────────────────────────────────────
    const text = collectDirectText(el);
    if (text) {
      const fontSize = Math.max(6, parseFloat(st.fontSize) * 0.75); // px → pt, min 6pt
      const colorHex = rgbToHex(st.color) ?? 'FFFFFF';
      const fontFace  = primaryFontFamily(st.fontFamily);
      const bold      = parseInt(st.fontWeight) >= 600;
      const italic    = st.fontStyle === 'italic';
      const underline = st.textDecorationLine?.includes('underline') ?? false;
      const align     = st.textAlign === 'center' ? 'center'
                      : st.textAlign === 'right'  ? 'right'
                      : 'left';

      slide.addText(text, {
        x: cx, y: cy, w: cw, h: ch,
        fontSize,
        bold,
        italic,
        underline,
        color: colorHex,
        fontFace,
        align,
        valign: 'top',
        wrap: true,
        fill:  { type: 'none' },
        line:  { type: 'none' },
      });
    }

    // Recurse into children
    for (const child of Array.from(el.children)) {
      await walk(child);
    }
  }

  // Start walk from direct children (background already handled for slideEl)
  for (const child of Array.from(slideEl.children)) {
    await walk(child);
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function downloadHtmlSlidePdf(
  html: string,
  title: string,
  onProgress?: (pct: number, msg: string) => void,
): Promise<void> {
  onProgress?.(5, 'Loading slides…');

  const [jspdfMod, h2cMod] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ]);
  type JsPDFCtor = typeof import('jspdf').default;
  const JsPDF: JsPDFCtor =
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (jspdfMod as any).jsPDF ?? jspdfMod.default;
  const h2canvas = (h2cMod.default ?? h2cMod) as typeof import('html2canvas').default;

  const iframe = await createSlideIframe(html);
  try {
    const doc = iframe.contentDocument!;
    const slides = findSlideElements(doc);

    const pdf = new JsPDF({
      orientation: 'landscape',
      unit: 'pt',
      format: [SLIDE_W_PT, SLIDE_H_PT],
      compress: true,
    });
    pdf.setProperties({ title, creator: 'ProDeck' });

    for (let i = 0; i < slides.length; i++) {
      onProgress?.(
        10 + Math.round((i / slides.length) * 85),
        `Capturing slide ${i + 1} of ${slides.length}…`,
      );

      const canvas = await h2canvas(slides[i], {
        scale:           2,
        useCORS:         true,
        allowTaint:      true,
        logging:         false,
        imageTimeout:    15000,
        backgroundColor: null,
        // Use the iframe's window so html2canvas resolves styles correctly
        windowWidth:     IFRAME_W,
        windowHeight:    IFRAME_H,
      });

      const imgData = canvas.toDataURL('image/jpeg', 0.92);
      if (i > 0) pdf.addPage([SLIDE_W_PT, SLIDE_H_PT], 'landscape');
      pdf.addImage(imgData, 'JPEG', 0, 0, SLIDE_W_PT, SLIDE_H_PT, '', 'FAST');
    }

    onProgress?.(97, 'Saving…');
    const safeName = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60) || 'presentation';
    pdf.save(`${safeName}.pdf`);
    onProgress?.(100, 'Done');
  } finally {
    removeIframe(iframe);
  }
}

export async function downloadHtmlSlidePptx(
  html: string,
  title: string,
  onProgress?: (pct: number, msg: string) => void,
): Promise<void> {
  onProgress?.(5, 'Loading slides…');

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { default: PptxGenJS } = await import('pptxgenjs') as any;
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE'; // 13.333" × 7.5"
  pptx.title  = title;
  pptx.author = 'ProDeck';

  const iframe = await createSlideIframe(html);
  try {
    const doc    = iframe.contentDocument!;
    const iWin   = iframe.contentWindow!;
    const slides = findSlideElements(doc);

    for (let i = 0; i < slides.length; i++) {
      onProgress?.(
        10 + Math.round((i / slides.length) * 85),
        `Converting slide ${i + 1} of ${slides.length}…`,
      );

      const slide = pptx.addSlide();
      await domToPptxSlide(slides[i], slide, iWin);
    }

    onProgress?.(97, 'Saving…');
    const safeName = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60) || 'presentation';
    await pptx.writeFile({ fileName: `${safeName}.pptx` });
    onProgress?.(100, 'Done');
  } finally {
    removeIframe(iframe);
  }
}
