/**
 * Planner types — defines the structure of execution plans.
 *
 * A Plan is a sequence of PlanSteps, each targeting a registered tool.
 * Plans are generated by the planner engine and executed by the plan executor.
 */

import type { ToolOutput } from '@ai-engine/core';

/** A single step in an execution plan. */
export interface PlanStep {
  /** Name of the tool to invoke (must exist in ToolRegistry). */
  tool: string;
  /** Input to pass to the tool's run() method. */
  input: Record<string, unknown>;
  /** Optional human-readable description of what this step does. */
  description?: string;
}

/** An ordered sequence of tool invocations. */
export interface Plan {
  steps: PlanStep[];
}

/** Input provided to the planner engine to generate a plan. */
export interface PlannerInput {
  /** High-level task description for the LLM to decompose. */
  task: string;
  /** Additional context the planner can use (document content, config, etc). */
  context?: Record<string, unknown>;
  /** List of tool names available for planning. */
  availableTools: string[];
}

/** Result of executing a single plan step. */
export interface StepResult {
  step: PlanStep;
  output: ToolOutput;
}

/** Result of executing an entire plan. */
export interface PlanExecutionResult {
  stepResults: StepResult[];
}

/**
 * Function signature for the LLM call used by the planner engine.
 *
 * The planner itself has no network access — the caller injects a
 * concrete implementation (e.g. Python subprocess bridge, direct API call).
 *
 * @param prompt  The full prompt to send to the LLM
 * @returns       The raw LLM response text (expected to be JSON)
 */
export type GenerateFn = (prompt: string) => Promise<string>;
